version: '3.8'

services:
  nodejs:
    image: node:19-buster
    environment:
      - HTTP_PORT=3000
      - NODE_ENV=development
      - AWS_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=""
      - AWS_SECRET_ACCESS_KEY=""
      - AWS_SESSION_TOKEN=""
    ports:
      - 3000:3000
    working_dir: /src
    volumes:
      - ./:/src
    command: npm run dev
