version: '3.8'

services:
  nodejs:
    image: node:19-buster
    environment:
      - HTTP_PORT=3000
      - NODE_ENV=development
      - AWS_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=ASIAXVBK4NFTU7IK2AYG
      - AWS_SECRET_ACCESS_KEY=2i32M275blj05n7D/qviESaCMFTIT67p1sfh9bhp
      - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEN7//////////wEaCXVzLWVhc3QtMiJGMEQCIAihfEZnOs5I68zXSG2+e+TkVcNo4bbka2aavAiGTRPpAiBYC572Dsh4CXRGPbelqKc44dWd3IUrJomKq7hJGL/9rCq3AgjH//////////8BEAAaDDUyNjIyMzQzNjEzNSIMsrm9YmGzzNnE7/LYKosCHY5Ea4tdeKe2v3+pulZ6j4PH0vuTn2/gPhQI6uGUdxEo91WOLyNIkk8jr6EWYv/FH3bJh+o4Ijbt7LFQDcoh9IpKDLd/5IKtqbfxQZGQ75gl/XfWHcO7/kUsGwDRZZNKl6AUw5lnVP0HCNn5jILTMtrLYiaJcFKQUyhYCkpGlVPRuIKzg9VlDCrnH5xNcyITA/0VHyt92H2xsO+Z1OsP4t39oKZmi1igCmrw39C0B4F9A5/AQp77McCvAbt7rzNr5nTFPbFLCMZHWXHtcfZWGZEr6vvbTJ0Hl1Q/72SXWe917vgcYTH1NAu2j6IprqWajJ5DMT0sRAPrC2bIIw1VNl1XATVZBe1jucKQMJ3X3KEGOp4BIm21z0gdXz1WdoK0ok3QM/RDm4nVgNNTa+A9VwB9nSWpezU5ZXervvcfILHeCDtlK2PdiGpjbHptDG/dUNsD+O6rLPU+hupSqED+vAV3GAlD0R/XKGMVrG6bPB8Sm6RmZ26V6/FasYhNIy3LplSBfgCbM3gKAlpfscEn2lE4vlToytF4LcLZW5Np8XIqPAp9eamrjtqvhqUR3RySXMA=
    ports:
      - 3000:3000
    working_dir: /src
    volumes:
      - ./:/src
    command: npm run dev
